var classes = [
    {
        "name": "App\\Builder\\CarBuilder",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildEngine",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildWheels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildSteering",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildBrakeSystem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getResult",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Builder\\IVehicleBuilder",
            "App\\Builder\\IEngineBuilder",
            "App\\Builder\\Vehicle"
        ],
        "parents": [],
        "lcom": 1,
        "length": 20,
        "vocabulary": 7,
        "volume": 56.15,
        "difficulty": 2.6,
        "effort": 145.98,
        "level": 0.38,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 21.6,
        "number_operators": 7,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 31,
        "lloc": 31,
        "mi": 55.08,
        "mIwoC": 55.08,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 1.58,
        "totalStructuralComplexity": 6,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 9.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Builder\\EngineBuilder",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildValves",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildSparkplug",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildPiston",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getResult",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Builder\\IEngineBuilder",
            "App\\Builder\\Vehicle"
        ],
        "parents": [],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 2,
        "effort": 82.72,
        "level": 0.5,
        "bugs": 0.01,
        "time": 5,
        "intelligentContent": 20.68,
        "number_operators": 8,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 25,
        "lloc": 25,
        "mi": 58.05,
        "mIwoC": 58.05,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 20,
        "totalSystemComplexity": 20,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Builder\\MotorcycleBuilder",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildEngine",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildWheels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildSteering",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildBrakeSystem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getResult",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Builder\\IVehicleBuilder",
            "App\\Builder\\IEngineBuilder",
            "App\\Builder\\Vehicle"
        ],
        "parents": [],
        "lcom": 1,
        "length": 20,
        "vocabulary": 7,
        "volume": 56.15,
        "difficulty": 2.6,
        "effort": 145.98,
        "level": 0.38,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 21.6,
        "number_operators": 7,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 31,
        "lloc": 31,
        "mi": 55.08,
        "mIwoC": 55.08,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 1.58,
        "totalStructuralComplexity": 6,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 9.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Builder\\Vehicle",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.04,
        "afferentCoupling": 4,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Builder\\VehicleBuilder",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildEngine",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildWheels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildSteering",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "BuildBrakeSystem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getResult",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Builder\\IVehicleBuilder",
            "App\\Builder\\IEngineBuilder",
            "App\\Builder\\Vehicle"
        ],
        "parents": [],
        "lcom": 1,
        "length": 20,
        "vocabulary": 7,
        "volume": 56.15,
        "difficulty": 2.6,
        "effort": 145.98,
        "level": 0.38,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 21.6,
        "number_operators": 7,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 31,
        "lloc": 31,
        "mi": 55.08,
        "mIwoC": 55.08,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 1.58,
        "totalStructuralComplexity": 6,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 9.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Builder\\VehicleDirector",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "build",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Builder\\IVehicleBuilder"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 4,
        "volume": 20,
        "difficulty": 4,
        "effort": 80,
        "level": 0.25,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 5,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 63.91,
        "mIwoC": 63.91,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 25.25,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 50.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ClickStatus",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.14,
        "afferentCoupling": 5,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "ClickChecker",
        "interface": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "succeedWith",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "next",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ClickStatus",
            "ClickChecker",
            "ClickStatus"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 2,
        "effort": 51.7,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 12.92,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 63.57,
        "mIwoC": 63.57,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.09,
        "afferentCoupling": 6,
        "efferentCoupling": 3,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "SanitizeCode",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 7,
        "lloc": 7,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.11,
        "afferentCoupling": 4,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "SanitizeChecker",
        "interface": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "succeedWith",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "next",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "SanitizeCode",
            "SanitizeChecker",
            "SanitizeCode"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 2,
        "effort": 51.7,
        "level": 0.5,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 12.92,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 63.57,
        "mIwoC": 63.57,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.07,
        "afferentCoupling": 5,
        "efferentCoupling": 3,
        "instability": 0.38,
        "violations": {}
    },
    {
        "name": "LeftClick",
        "interface": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ClickChecker",
            "ClickStatus"
        ],
        "parents": [
            "ClickChecker"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 7,
        "volume": 22.46,
        "difficulty": 0.58,
        "effort": 13.1,
        "level": 1.71,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 38.5,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 65.97,
        "mIwoC": 65.97,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "MiddleClick",
        "interface": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ClickChecker",
            "ClickStatus"
        ],
        "parents": [
            "ClickChecker"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 7,
        "volume": 22.46,
        "difficulty": 0.58,
        "effort": 13.1,
        "level": 1.71,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 38.5,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 65.97,
        "mIwoC": 65.97,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "NullClick",
        "interface": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ClickChecker",
            "ClickStatus"
        ],
        "parents": [
            "ClickChecker"
        ],
        "lcom": 1,
        "length": 7,
        "vocabulary": 6,
        "volume": 18.09,
        "difficulty": 0.6,
        "effort": 10.86,
        "level": 1.67,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 30.16,
        "number_operators": 1,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 66.63,
        "mIwoC": 66.63,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "RightClick",
        "interface": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ClickChecker",
            "ClickStatus"
        ],
        "parents": [
            "ClickChecker"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 7,
        "volume": 22.46,
        "difficulty": 0.58,
        "effort": 13.1,
        "level": 1.71,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 38.5,
        "number_operators": 1,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 65.97,
        "mIwoC": 65.97,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "SanitizeHtmlStepResponsibility",
        "interface": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "SanitizeChecker",
            "SanitizeCode"
        ],
        "parents": [
            "SanitizeChecker"
        ],
        "lcom": 1,
        "length": 10,
        "vocabulary": 7,
        "volume": 28.07,
        "difficulty": 1.6,
        "effort": 44.92,
        "level": 0.63,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 17.55,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 66.87,
        "mIwoC": 66.87,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "SanitizeJsStepResponsibility",
        "interface": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "SanitizeChecker",
            "SanitizeCode"
        ],
        "parents": [
            "SanitizeChecker"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 10,
        "volume": 39.86,
        "difficulty": 1.93,
        "effort": 76.88,
        "level": 0.52,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 20.67,
        "number_operators": 3,
        "number_operands": 9,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 64.98,
        "mIwoC": 64.98,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "SanitizeSqlStepResponsibility",
        "interface": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "SanitizeChecker",
            "SanitizeCode"
        ],
        "parents": [
            "SanitizeChecker"
        ],
        "lcom": 1,
        "length": 12,
        "vocabulary": 10,
        "volume": 39.86,
        "difficulty": 1.93,
        "effort": 76.88,
        "level": 0.52,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 20.67,
        "number_operators": 3,
        "number_operands": 9,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 12,
        "lloc": 12,
        "mi": 64.98,
        "mIwoC": 64.98,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ExceptionHandlingBehaviorDecorator",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "exception",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ReverseBehavior",
            "Exception"
        ],
        "parents": [],
        "lcom": 1,
        "length": 13,
        "vocabulary": 10,
        "volume": 43.19,
        "difficulty": 3,
        "effort": 129.56,
        "level": 0.33,
        "bugs": 0.01,
        "time": 7,
        "intelligentContent": 14.4,
        "number_operators": 4,
        "number_operands": 9,
        "number_operators_unique": 4,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 20,
        "lloc": 20,
        "mi": 59.9,
        "mIwoC": 59.9,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 4.33,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 8.67,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "InterceptionBehaviorDecorator",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "intercept",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "LoggingModifyBehaviorDecorater"
        ],
        "parents": [],
        "lcom": 1,
        "length": 17,
        "vocabulary": 10,
        "volume": 56.47,
        "difficulty": 3.67,
        "effort": 207.07,
        "level": 0.27,
        "bugs": 0.02,
        "time": 12,
        "intelligentContent": 15.4,
        "number_operators": 6,
        "number_operands": 11,
        "number_operators_unique": 4,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 60.08,
        "mIwoC": 60.08,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "LoggingModifyBehaviorDecorater",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "ReverseBehavior"
        ],
        "parents": [],
        "lcom": 1,
        "length": 15,
        "vocabulary": 9,
        "volume": 47.55,
        "difficulty": 2.5,
        "effort": 118.87,
        "level": 0.4,
        "bugs": 0.02,
        "time": 7,
        "intelligentContent": 19.02,
        "number_operators": 5,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 63.12,
        "mIwoC": 63.12,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "NullBehaviorDecorator",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rejectExecution",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "LoggingModifyBehaviorDecorater",
            "ReverseBehavior"
        ],
        "parents": [],
        "lcom": 2,
        "length": 10,
        "vocabulary": 5,
        "volume": 23.22,
        "difficulty": 2.33,
        "effort": 54.18,
        "level": 0.43,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 9.95,
        "number_operators": 3,
        "number_operands": 7,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 64.65,
        "mIwoC": 64.65,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ReverseBehavior",
        "interface": false,
        "methods": [
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "IModifyBehavior"
        ],
        "parents": [],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 1,
        "effort": 3,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 3,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 76.82,
        "mIwoC": 76.82,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "pageRank": 0.1,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "violations": {}
    },
    {
        "name": "TimeBehaviorDecorator",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculateExecutionTime",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "ReverseBehavior"
        ],
        "parents": [],
        "lcom": 1,
        "length": 20,
        "vocabulary": 10,
        "volume": 66.44,
        "difficulty": 2.79,
        "effort": 185.08,
        "level": 0.36,
        "bugs": 0.02,
        "time": 10,
        "intelligentContent": 23.85,
        "number_operators": 7,
        "number_operands": 13,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 60.26,
        "mIwoC": 60.26,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 4,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]